markdown: rdiscount
permalink: /:title/
markdown: rdiscount
url: peakerwd.com
name: peakerwd.com
author: 王渡
qq: 4609747
email: peakerwd@gmail.com
weibo: 1734372240
github: peakerwd
duoshuo: peakerWd
pygments: true
safe: true
paginate: 20
about: 王渡的博客
